# @package _global_
# Check flan-t5-base.yaml for base config.

defaults:
  - flan-t5-base

model:
  model_name_or_path: google/flan-t5-xl

training:
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 4
