# @package _global_

defaults:
  - flan-t5-large

data:
  max_eval_samples: 10

training:
  per_device_train_batch_size: 1
  logging_steps: 1
  eval_steps: 5
  save_steps: 5
  max_steps: 5

wandb:
  name: debug
  log: false